version: '3'

services:
  node:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    tty: true
    volumes:
      - .:/src
    working_dir: "/src"
    ports:
      - 8080:8080
    command: >
      sh -c "npm run build &&
             npm start"
